name: GitHub Actions test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: test-step
        shell: bash
        run: |
          echo 'hello'
          ls -la

