name: Otameshi-GHA

on:
  #schedule:
  #  - cron: '0/5 * * * *'
  workflow_dispatch:
    inputs:
      no-cache:
        description: 'this is description'
        default: false
        required: false
        type: boolean
  push:
    tags:
      - v*
  #workflow_run:
  #  workflows: ["Otameshi-trigger"]
  #  types: ["completed"]
  workflow_call:
    inputs:
      newtag:
        description: '新しいタグ'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get-revision
        shell: bash
        run: |
          env
        env:
          newtag: ${{ inputs.newtag }}

      - uses: actions/checkout@v3
        with:
          ref: ""

      - name: test-step
        shell: bash
        run: |
          echo 'hello'
          ls -la
          env
          git log
