name: Otameshi-GHA

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0/5 * * * *'
  workflow_dispatch:
    inputs:
      no-cache:
        description: 'this is description'
        default: false
        required: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: test-step
        shell: bash
        run: |
          echo 'hello'
          ls -la
          env
          git log
