name: Otameshi-GHA

on:
  #schedule:
  #  - cron: '0/5 * * * *'
  workflow_dispatch:
    inputs:
      no-cache:
        description: 'this is description'
        default: false
        required: false
        type: boolean
  push:
    tags:
      - v*
  workflow_run:
    workflows: ["Otameshi-trigger"]
    types: ["completed"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: test-step
        shell: bash
        run: |
          echo 'hello'
          ls -la
          env
          git log
