name: Otameshi-trigger

on:
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: trigger
        name: trigger
        shell: bash
        run: |
          set -ux
          echo ${gh_token:0:4}
          git remote add target "https://akihiro-nagai:${gh_token}@github.com/akihiro-nagai/actions-test.git"
          git remote -v
          git remote update target
          ver=v$(date '+%Y.%m.%d-%H%M%S')
          git tag "${ver}"
          git push target "${ver}"
          echo "newtag=${ver}" >> "${GITHUB_OUTPUT}"
        env:
          gh_token: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      newtag: ${{ steps.trigger.outputs.newtag }}

#  call-main:
#    needs: trigger
#    uses: ./.github/workflows/test.yaml
#    with:
#      newtag: ${{ needs.trigger.outputs.newtag }}
